### ISSUE TITLE
Broken paths and exceptions in Windows 7

### ISSUE THREAD

**Issue by JeanPaulLucien** [yggdrasil-network/yggdrasil-go#1014]
Yggdrasil version: 0.4.7
OS: 64-bit
I used an information from Readme to prepare for work.

```
c:\Program Files\Yggdrasil>yggdrasil.exe -useconffile > c:/program files/yggdras
il/yggdrasil.conf
panic: open files/yggdrasil/yggdrasil.conf: The system cannot find the path spec
ified.

goroutine 21 [running]:
main.readConfig(0x7232ff?, 0x4?, {0xc0000a4060?, 0x5?}, 0x0?)
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:61 +0x27d
main.run({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0xc0000a4060, 0x1e}, ...}, ..
.)
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:226 +0x9ac main.main.func1()
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:405 +0x85 created by main.main
        D:/a/yggdrasil-go/yggdrasil-go/cmd/yggdrasil/main.go:403 +0x1b7
```
1. You should replace `panic` by normal code.
2. Strange something are going with path of Yggdrasil.

**Comment by neilalexander** [comment]
If there are spaces in the path, you must surround them with quote marks, i.e. `-useconffile "C:\Program Files\Yggdrasil\yggdrasil.conf"`
