### ISSUE TITLE
Panics on Debian Stretch (0.3.5)

### ISSUE THREAD

**Issue by misuzu** [yggdrasil-network/yggdrasil-go#414]
```bash
% uname -a
Linux localhost 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
```
```
Apr 24 15:41:53 localhost systemd[1]: Starting yggdrasil...
Apr 24 15:41:53 localhost systemd[1]: Started yggdrasil.
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Build name: yggdrasil
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Build version: 0.3.5
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Starting up...
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Starting switch
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Starting router
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Multicast discovery is disabled
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Interface name: tun0
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Interface IPv6: <edited>
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Interface MTU: 65535
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Startup complete
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Your IPv6 address is <edited>
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Your IPv6 subnet is <edited>
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Listening for TCP on: [::]:30466
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 UNIX admin socket listening on /var/run/yggdrasil.sock
Apr 24 15:41:53 localhost yggdrasil[9835]: 2019/04/24 15:41:53 Connected TCP: <edited>
Apr 24 15:41:54 localhost yggdrasil[9835]: 2019/04/24 15:41:54 Connected TCP: <edited>
Apr 24 15:41:55 localhost yggdrasil[9835]: 2019/04/24 15:41:55 Connected TCP: <edited>
Apr 24 15:41:56 localhost yggdrasil[9835]: 2019/04/24 15:41:56 Connected TCP: <edited>
Apr 24 15:43:32 localhost yggdrasil[9835]: panic: write /dev/net/tun: no buffer space available
Apr 24 15:43:32 localhost yggdrasil[9835]: goroutine 40 [running]:
Apr 24 15:43:32 localhost yggdrasil[9835]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).write(0xc0000bf7a0, 0x0, 0x0)
Apr 24 15:43:32 localhost yggdrasil[9835]:         /home/circleci/project/src/yggdrasil/tun.go:201 +0x9a3
Apr 24 15:43:32 localhost yggdrasil[9835]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start.func2(0xc0000bf7a0)
Apr 24 15:43:32 localhost yggdrasil[9835]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2f
Apr 24 15:43:32 localhost yggdrasil[9835]: created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start
Apr 24 15:43:32 localhost yggdrasil[9835]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2c1
Apr 24 15:43:32 localhost systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 15:43:32 localhost systemd[1]: yggdrasil.service: Unit entered failed state.
Apr 24 15:43:32 localhost systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Apr 24 15:43:32 localhost systemd[1]: yggdrasil.service: Service hold-off time over, scheduling restart.
Apr 24 15:43:32 localhost systemd[1]: Stopped yggdrasil.
Apr 24 15:43:32 localhost systemd[1]: Starting yggdrasil...
Apr 24 15:43:32 localhost systemd[1]: Started yggdrasil.
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Build name: yggdrasil
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Build version: 0.3.5
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Starting up...
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Starting switch
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Starting router
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Multicast discovery is disabled
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Interface name: tun0
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Interface IPv6: <edited>
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Interface MTU: 65535
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Startup complete
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Your IPv6 address is <edited>
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Your IPv6 subnet is <edited>
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 UNIX admin socket listening on /var/run/yggdrasil.sock
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Listening for TCP on: [::]:30466
Apr 24 15:43:32 localhost yggdrasil[9880]: 2019/04/24 15:43:32 Connected TCP: <edited>
Apr 24 15:43:33 localhost yggdrasil[9880]: 2019/04/24 15:43:33 Connected TCP: <edited>
Apr 24 15:43:34 localhost yggdrasil[9880]: 2019/04/24 15:43:34 Connected TCP: <edited>
Apr 24 15:43:35 localhost yggdrasil[9880]: 2019/04/24 15:43:35 Connected TCP: <edited>
Apr 24 15:45:18 localhost yggdrasil[9880]: panic: write /dev/net/tun: no buffer space available
Apr 24 15:45:18 localhost yggdrasil[9880]: goroutine 40 [running]:
Apr 24 15:45:18 localhost yggdrasil[9880]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).write(0xc0000bf7a0, 0x0, 0x0)
Apr 24 15:45:18 localhost yggdrasil[9880]:         /home/circleci/project/src/yggdrasil/tun.go:201 +0x9a3
Apr 24 15:45:18 localhost yggdrasil[9880]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start.func2(0xc0000bf7a0)
Apr 24 15:45:18 localhost yggdrasil[9880]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2f
Apr 24 15:45:18 localhost yggdrasil[9880]: created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start
Apr 24 15:45:18 localhost yggdrasil[9880]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2c1
Apr 24 15:45:18 localhost systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 15:45:18 localhost systemd[1]: yggdrasil.service: Unit entered failed state.
Apr 24 15:45:18 localhost systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Apr 24 15:45:18 localhost systemd[1]: yggdrasil.service: Service hold-off time over, scheduling restart.
Apr 24 15:45:18 localhost systemd[1]: Stopped yggdrasil.
Apr 24 15:45:18 localhost systemd[1]: Starting yggdrasil...
Apr 24 15:45:18 localhost systemd[1]: Started yggdrasil.
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Build name: yggdrasil
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Build version: 0.3.5
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Starting up...
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Starting switch
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Starting router
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Multicast discovery is disabled
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Interface name: tun0
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Interface IPv6: <edited>
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Interface MTU: 65535
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Startup complete
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Your IPv6 address is <edited>
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Your IPv6 subnet is <edited>
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Listening for TCP on: [::]:30466
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 UNIX admin socket listening on /var/run/yggdrasil.sock
Apr 24 15:45:18 localhost yggdrasil[9966]: 2019/04/24 15:45:18 Connected TCP: <edited>
Apr 24 15:45:19 localhost yggdrasil[9966]: 2019/04/24 15:45:19 Connected TCP: <edited>
Apr 24 15:45:20 localhost yggdrasil[9966]: 2019/04/24 15:45:20 Connected TCP: <edited>
Apr 24 15:45:21 localhost yggdrasil[9966]: 2019/04/24 15:45:21 Connected TCP: <edited>
Apr 24 16:10:06 localhost yggdrasil[9966]: panic: write /dev/net/tun: no buffer space available
Apr 24 16:10:06 localhost yggdrasil[9966]: goroutine 27 [running]:
Apr 24 16:10:06 localhost yggdrasil[9966]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).write(0xc0000a57a0, 0x0, 0x0)
Apr 24 16:10:06 localhost yggdrasil[9966]:         /home/circleci/project/src/yggdrasil/tun.go:201 +0x9a3
Apr 24 16:10:06 localhost yggdrasil[9966]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start.func2(0xc0000a57a0)
Apr 24 16:10:06 localhost yggdrasil[9966]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2f
Apr 24 16:10:06 localhost yggdrasil[9966]: created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start
Apr 24 16:10:06 localhost yggdrasil[9966]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2c1
Apr 24 16:10:06 localhost systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 16:10:06 localhost systemd[1]: yggdrasil.service: Unit entered failed state.
Apr 24 16:10:06 localhost systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Apr 24 16:10:06 localhost systemd[1]: yggdrasil.service: Service hold-off time over, scheduling restart.
Apr 24 16:10:06 localhost systemd[1]: Stopped yggdrasil.
Apr 24 16:10:06 localhost systemd[1]: Starting yggdrasil...
Apr 24 16:10:07 localhost systemd[1]: Started yggdrasil.
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Build name: yggdrasil
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Build version: 0.3.5
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Starting up...
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Starting switch
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Starting router
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Multicast discovery is disabled
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Interface name: tun0
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Interface IPv6: <edited>
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Interface MTU: 65535
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Startup complete
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Your IPv6 address is <edited>
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Your IPv6 subnet is <edited>
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Listening for TCP on: [::]:30466
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 UNIX admin socket listening on /var/run/yggdrasil.sock
Apr 24 16:10:07 localhost yggdrasil[10581]: 2019/04/24 16:10:07 Connected TCP: <edited>
Apr 24 16:10:08 localhost yggdrasil[10581]: 2019/04/24 16:10:08 Connected TCP: <edited>
Apr 24 16:10:09 localhost yggdrasil[10581]: 2019/04/24 16:10:09 Connected TCP: <edited>
Apr 24 16:10:10 localhost yggdrasil[10581]: 2019/04/24 16:10:10 Connected TCP: <edited>
Apr 24 16:10:28 localhost yggdrasil[10581]: panic: write /dev/net/tun: no buffer space available
Apr 24 16:10:28 localhost yggdrasil[10581]: goroutine 41 [running]:
Apr 24 16:10:28 localhost yggdrasil[10581]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).write(0xc0000fcea0, 0x0, 0x0)
Apr 24 16:10:28 localhost yggdrasil[10581]:         /home/circleci/project/src/yggdrasil/tun.go:201 +0x9a3
Apr 24 16:10:28 localhost yggdrasil[10581]: github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start.func2(0xc0000fcea0)
Apr 24 16:10:28 localhost yggdrasil[10581]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2f
Apr 24 16:10:28 localhost yggdrasil[10581]: created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start
Apr 24 16:10:28 localhost yggdrasil[10581]:         /home/circleci/project/src/yggdrasil/tun.go:86 +0x2c1
Apr 24 16:10:28 localhost systemd[1]: yggdrasil.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 16:10:28 localhost systemd[1]: yggdrasil.service: Unit entered failed state.
Apr 24 16:10:28 localhost systemd[1]: yggdrasil.service: Failed with result 'exit-code'.
Apr 24 16:10:28 localhost systemd[1]: yggdrasil.service: Service hold-off time over, scheduling restart.
Apr 24 16:10:28 localhost systemd[1]: Stopped yggdrasil.
```

**Comment by misuzu** [comment]
Triggered on my machine by ncdc client on adc://[202:9877:2815:cd91:336:2a16:bfd9:7258]:1511
After requesting filelists from multiple users yggdrasil panics immediately

**Comment by neilalexander** [comment]
If you drop the `IfMTU` value in your `yggdrasil.conf` down to a lower number (the default on Linux is 65535 but you could try 9000 or something), does the problem persist?

This looks suspiciously similar to #319 so it might be that also some of the `sysctl` bits there are also relevant.

**Comment by misuzu** [comment]
@neilalexander 

Yes, setting IfMTU to 9000 fixes the issue.

```bash
% sysctl net.core.wmem_default
net.core.wmem_default = 212992
% sysctl net.core.wmem_max
net.core.wmem_max = 16777216
% sysctl net.core.rmem_default
net.core.rmem_default = 212992
% sysctl net.core.rmem_max
net.core.rmem_max = 16777216
```

**Comment by neilalexander** [comment]
Hm okay, this is interesting. You could try increasing `IfMTU` to 16384, 32768 etc incrementally until you reproduce the issue. I suspect we may need to look into the behaviour of the TUN/TAP buffers more closely.

**Comment by misuzu** [comment]
@neilalexander 
IfMTU: 32767 - ok
IfMTU: 32768 - panic

**Comment by neilalexander** [comment]
When you get the opportunity, can you please test with the latest `develop` builds and see if this is still an issue?

**Comment by misuzu** [comment]
@neilalexander well, i can't reproduce this bug even on 0.3.5.
Maybe because i moved to 4.19 kernel

**Comment by neilalexander** [comment]
OK, I'll close the issue for now. Please reopen it if you experience the problem again.
