### ISSUE TITLE
FreeBSD - panic: write /dev/tap0: input/output error

### ISSUE THREAD

**Issue by Demindiro** [yggdrasil-network/yggdrasil-go#459]
After trying to figure out why `tap0` was brought down and up again for seemingly no reason, causing the `200::/7` route to disappear I ran `yggdrasil -useconffile /usr/local/etc/yggdrasil.conf` manually. After a while I got this error:

```
panic: write /dev/tap0: input/output error

goroutine 30 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).write(0xc0000a17a0, 0x0, 0x0)
	/root/yggdrasil-go/src/yggdrasil/tun.go:189 +0x9c8
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start.func2(0xc0000a17a0)
	/root/yggdrasil-go/src/yggdrasil/tun.go:86 +0x2f
created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tunAdapter).start
	/root/yggdrasil-go/src/yggdrasil/tun.go:86 +0x2ce
```

`yggdrasil` subsequently stopped and `tap0` was brought down, which results in the route being removed.

I have (temporarily) adapted `contrib/freebsd/yggdrasil` to add the route again if `yggdrasil` crashes.

Version of Yggdrasil I'm using:

```
# yggdrasil --version
Build name: yggdrasil
Build version: 0.3.5
```

---

There are some other changes to the script too:
- The configuration file is now located in `/usr/local/etc` instead of `/etc`
- The `-f` flag for `daemon(8)` causes all output to be written to `/dev/null`. This is why the logs are always empty.
  Excerpt from `man daemon`:
    ```
     -f      Redirect standard input, standard output and standard error to
             /dev/null.
    ```
    I have replaced `-f` with `-o /var/log/yggdrasil.log` and removed `/var/log/yggdrasil.std{err,out}.log`.

I'll make a pull request for the script later.

---

Since Github "doesn't support that file type", I'll just paste it here:

```
#!/bin/sh
#
# Put the yggdrasil and yggdrasilctl binaries into /usr/local/bin
# Then copy this script into /usr/local/etc/rc.d/yggdrasil
# Finally, run:
#   1. chmod +x /usr/local/etc/rc.d/yggdrasil /usr/local/bin/{yggdrasil,yggdrasilctl}
#   2. echo "yggdrasil_enable=yes" >> /usr/local/etc/rc.conf
#   3. service yggdrasil start
#
# PROVIDE: yggdrasil
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="yggdrasil"
rcvar="yggdrasil_enable"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

pidfile="/var/run/yggdrasil/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -o /var/log/yggdrasil.log"

yggdrasil_start()
{
	test ! -x /usr/local/bin/yggdrasil && (
		logger -s -t yggdrasil "Warning: /usr/local/bin/yggdrasil is missing or not executable"
		logger -s -t yggdrasil "Copy the yggdrasil binary into /usr/local/bin and then chmod +x /usr/local/bin/yggdrasil"
		return 1
	)

	test ! -f /usr/local/etc/yggdrasil.conf && (
		logger -s -t yggdrasil "Generating new configuration file into /usr/local/etc/yggdrasil.conf"
		/usr/local/bin/yggdrasil -genconf > /usr/local/etc/yggdrasil.conf
	)

	tap_path="$(cat /usr/local/etc/yggdrasil.conf | egrep -o '/dev/tap[0-9]{1,2}$')"
	tap_name="$(echo -n ${tap_path} | tr -d '/dev/')"

	/sbin/ifconfig ${tap_name} >/dev/null 2>&1 || (
		logger -s -t yggdrasil "Creating ${tap_name} adapter"
		/sbin/ifconfig ${tap_name} create || logger -s -t yggdrasil "Failed to create ${tap_name} adapter"
	)

	test ! -d /var/run/yggdrasil && mkdir -p /var/run/yggdrasil

	logger -s -t yggdrasil "Starting yggdrasil"
	${command} ${command_args} sh -c \
		"/usr/local/bin/yggdrasil -useconffile /usr/local/etc/yggdrasil.conf;
		route -6 add -net 200::/7 -interface ${tap_name}"
}

yggdrasil_stop()
{
	logger -s -t yggdrasil "Stopping yggdrasil"
	test -f /var/run/yggdrasil/${name}.pid && kill -TERM $(cat /var/run/yggdrasil/${name}.pid)

	tap_path="$(cat /usr/local/etc/yggdrasil.conf | grep /dev/tap | egrep -o '/dev/.*$')"
        tap_name="$(echo -n ${tap_path} | tr -d '/dev/')"

	/sbin/ifconfig ${tap_name} >/dev/null 2>&1 && (
		logger -s -t yggdrasil "Destroying ${tap_name} adapter"
		/sbin/ifconfig ${tap_name} destroy || logger -s -t yggdrasil "Failed to destroy ${tap_name} adapter"
	)
}

load_rc_config $name
: ${yggdrasil_enable:=no}

run_rc_command "$1"
```

**Comment by neilalexander** [comment]
We'll need to investigate that crash, but the latest FreeBSD package sources are at https://github.com/yggdrasil-network/yggdrasil-package-freebsd and it would be best to point PRs there. :-)

Honestly the package could use a lot of work but I'm not a day-to-day FreeBSD user so it has slipped down the list somewhat. I did submit a port as well but seemingly that's gone nowhere for months.

**Comment by neilalexander** [comment]
Can you please test if you still get the `input/output` error on the [latest `develop` builds](https://yggdrasil-network.github.io/builds-develop.html)?

**Comment by Demindiro** [comment]
The error seems to be gone.

Thank you!
