### ISSUE TITLE
Leaking link handler goroutines

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#501]
There are lots of these happening:
```
goroutine 245429 [chan receive, 87 minutes]:
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*linkInterface).handler(0xc0000b8840, 0x0, 0x0)
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/link.go:182 +0x15af
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tcp).handler(0xc0000d3190, 0x9aa8e0, 0xc00000e568, 0xc00005e601, 0x0, 0x0)
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/tcp.go:349 +0x5a2
created by github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*tcp).listener
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/tcp.go:198 +0x281
```
... which looks like they're not being cleaned up properly when a link is going down, or when a new incoming dial is handled for a node that we already have a connection to.

https://github.com/yggdrasil-network/yggdrasil-go/blob/develop/src/yggdrasil/link.go#L182

**Comment by neilalexander** [comment]
This seems to be fixed by #502.
