### ISSUE TITLE
Nil pointer dereference while receiving message

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#533]
Problem happened with version `0.3.8-0080`.
First of all, one of addresses became unavailable.
The one, which starts with `303:`.
Then, after some time, Yggdrasil server crashed.
Since logging for Windows service is disabled, I can't say exactly what happened.
Restarted it in console mode now and will wait for a crash.
If it reproduces, I will update report, if not - will close it.

**Comment by Vort** [comment]
Here is the crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5990ad]

goroutine 1696296 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*Conn).recvMsg(0x0, 0x6
baa80, 0xc0003c8240, 0xc0001d0000, 0x144, 0x178)
        /home/circleci/project/src/yggdrasil/conn.go:184 +0x7d
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*sessionInfo)._recvPack
et.func1.1()
        /home/circleci/project/src/yggdrasil/session.go:479 +0x18c
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*sessionInfo).checkCall
backs.func1()
        /home/circleci/project/src/yggdrasil/session.go:537 +0xcf
github.com/Arceliar/phony.(*Inbox).run(0xc0003c8240)
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20190831214819-9b642ea019a
d/actor.go:83 +0x12d
created by github.com/Arceliar/phony.(*Inbox).enqueue
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20190831214819-9b642ea019a
d/actor.go:51 +0xda
```
