### ISSUE TITLE
Conn.recvMsg occasionally panics with sinfo.conn nil pointer

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#549]
I've come across some crashes like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41ca98]

goroutine 12126 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*Conn).recvMsg(0x0, 0x694a80, 0xc4a5a0, 0xe8a000, 0x89, 0x240)
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/conn.go:186 +0x90
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*sessionInfo)._recvPacket.func1.1()
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/session.go:479 +0x1a4
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*sessionInfo).checkCallbacks.func1()
	/Users/neilalexander/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/session.go:537 +0xd8
github.com/Arceliar/phony.(*Inbox).run(0xc4a5a0)
	/Users/neilalexander/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20190907031509-af5bdbeecab6/actor.go:96 +0xe0
created by github.com/Arceliar/phony.(*Inbox).restart
	/Users/neilalexander/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20190907031509-af5bdbeecab6/actor.go:127 +0x50
```

**Comment by neilalexander** [comment]
@Arceliar Any ideas on this one?

**Comment by neilalexander** [comment]
This hasn’t happened recently and might have been fixed by some of @Arceliar’s work on the session/conn pointers. I’ll remove this from the v0.3.9 milestone for now but I’ll keep the issue open as a reminder to test this further.

**Comment by neilalexander** [comment]
Closing this as I haven't seen a repeat of it recently.
