### ISSUE TITLE
Android TUN adapter is at /dev/tun instead of /dev/net/tun

### ISSUE THREAD

**Issue by r4sas** [yggdrasil-network/yggdrasil-go#633]
I built ygg binary via termux for arm64 and trying start it.
App is crashing with goroutine:
```
$ tsudo bin/yggdrasil -useconffile yggdrasil.conf
2019/12/04 09:07:37 Build name: yggdrasil-develop
2019/12/04 09:07:37 Build version: 0.3.12-0050
2019/12/04 09:07:37 Starting up...
2019/12/04 09:07:37 Starting switch
2019/12/04 09:07:37 Starting router
2019/12/04 09:07:37 Startup complete
2019/12/04 09:07:37 Starting multicast module
panic: no such file or directory

goroutine 66 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0x400015a000, 0x40000167e8, 0x8, 0x40001b6030, 0x28, 0xffff, 0x28, 0x2673c088afebaa79)
        /data/data/com.termux/files/home/dev/yggdrasil-go/src/tuntap/tun_linux.go:19 +0x1f0
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0x400015a000, 0x0, 0x0)
        /data/data/com.termux/files/home/dev/yggdrasil-go/src/tuntap/tun.go:162 +0x320
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        /data/data/com.termux/files/home/dev/yggdrasil-go/src/tuntap/tun.go:135 +0x28
github.com/Arceliar/phony.Block.func1()
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:89 +0x28
github.com/Arceliar/phony.(*Inbox).run(0x400015a168)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:104 +0x9c
created by github.com/Arceliar/phony.(*Inbox).restart
        /data/data/com.termux/files/home/go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:130 +0x34
```

**Comment by neilalexander** [comment]
Can you please check the existence of `/dev/net/tun` and `/dev/tun` on your system?

**Comment by r4sas** [comment]
/dev/tun exists
![Screenshot_20191204-092830_1](https://user-images.githubusercontent.com/7023612/70130534-9fbbe800-1678-11ea-8350-025831a4b272.png)

**Comment by neilalexander** [comment]
OK, that's the problem. I think that currently we only test the presence of `/dev/net/tun`. For now you could try doing this:
```
ln -s /dev/tun /dev/net/tun
```

**Comment by r4sas** [comment]
Yes, that make a trick.

**Comment by r4sas** [comment]
I think better check both places, that can depend on manufacturer who built system.

**Comment by neilalexander** [comment]
I've marked this as `external dependency` because this is actually a problem in upstream packages and not in the Yggdrasil source itself.

**Comment by r4sas** [comment]
ref: https://git.zx2c4.com/wireguard-go/tree/tun/tun_linux.go?id=ddfad453cf22146e9476a5f4b91cf6c47b77e9c7#n28
