### ISSUE TITLE
SIGSEGV: segmentation violation code=0x1 addr=0x700 pc=0x65d48f]

### ISSUE THREAD

**Issue by kravietz** [yggdrasil-network/yggdrasil-go#670]
```
# yggdrasil -useconffile /etc/yggdrasil.conf
2020/03/31 10:39:50 Build name: yggdrasil
2020/03/31 10:39:50 Build version: 0.3.13
2020/03/31 10:39:50 Starting up...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x700 pc=0x65d48f]

goroutine 16 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*switchTable).start(...)
        /home/circleci/project/src/yggdrasil/switch.go:582
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*Core)._start(0xc000116800, 0xc0000ce900, 0xc00006ea20, 0x0, 0x0, 0x0)
        /home/circleci/project/src/yggdrasil/core.go:170 +0x30f
github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*Core).Start.func1()
        /home/circleci/project/src/yggdrasil/core.go:141 +0x52
github.com/Arceliar/phony.Block.func1()
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:89
+0x2f
github.com/Arceliar/phony.(*Inbox).run(0xc000116800)
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:104 +0x8d
created by github.com/Arceliar/phony.(*Inbox).restart
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:130 +0x3f
```
With the following config file (perhaps some syntax errors are causing it but it shouldn't SIGSEGV anyway):
```
{
  "Peers": [
        "tcp://[2001:19f0:7402:431:5400:2ff:fe21:7912]:8082"

  ],
  "InterfacePeers": {},
  "Listen": [
        "tcp://[::]:8082"

  ],
  "AdminListen": "unix:///var/run/yggdrasil.sock",
  "MulticastInterfaces": [
        ".*"

  ],
  "AllowedEncryptionPublicKeys": [
            "0446373d6df4a48ea1b8572cc59409a40bbed7393cf93a37f34f90427b222319"

            "812862be3257c7cedde9cd552e0bdf2d3bee1e903c47c4a405832dbac730b448"

            "8238e73f4ee16a02fe3ad82d3d8b61ab0abc41ade2b1d5a591123581401da672"

            "df3ed963b16e65c5d2d4dfdb8f95efd3c6332b5d66c81067aaf43df58e71fd10"

            "e81a314e6cbede9ea973271dbd52342e1eb18ab04c44a81b54020d84131bbe3e"

            "920a7bcbe3059f5127dc188d21e9afea30d1a6573cd74adcdac9de1edbdf0976"

            "ed48e09f041315bccb57caf787981b2ee8f4f61e9557e6d02993561edef70721"

            "1789419647a9a68f82d7c1eee8f3d4948f5e1b97c00fabbbb858709a7c268b7b"

            "72fa93c9437b939272fba21a1d243210b1b5c2462ed99e7ce5eb12854e45dd00"

            "3c5b97b2fddfe09d395317776a3dc488a9ad0e5cfc5fa17e795a4b376bbb8028"

            "8c54d14a2f5f21714538d9600803e778a6e0c2b2d22eac65e1653ed188269b73"

            "ff1d9d9f6bfc1820a0d3b36f882b8df95678aa699ae5d49ca608bb200803a972"

      ],
  "EncryptionPublicKey": "53fe55fd1daab470936f85e1aa1f4b16190b541c6daa6feb41bcc70a63000f5b",
  "EncryptionPrivateKey": "0anf89d49f064971160cd80250deae1bfaf4901a2ce0b64082a905068fb0b3cf",
  "SigningPublicKey": "95b61c31f3c0e04eba6dbc97686d8f3f39c21fee7728053c5ed0e4bd022868a2",
  "SigningPrivateKey": "acefa02d1357831159db3bc46671cc22ec83a92a4f593ca0374ef03222ed530e95b61c31f3c0e04eba6dbc97686d8f3f39c21fee7728053c5ed0e4bd022868a2",
  "LinkLocalTCPPort": 8081,
  "IfName": "auto",
  "IfTAPMode": false,
  "IfMTU": 65535,
  "SessionFirewall": {
    "Enable": false,
    "AllowFromDirect": true,
    "AllowFromRemote": true,
    "AlwaysAllowOutbound": true,
    "WhitelistEncryptionPublicKeys": [
    ],
    "BlacklistEncryptionPublicKeys": [
    ]
  },
  "TunnelRouting": {
    "Enable": false,
    "IPv6Destinations": {
    },
    "IPv6Sources": [
    ],
    "IPv4Destinations": {
    },
    "IPv4Sources": [
            ]
  },
  "SwitchOptions": {
    "MaxTotalQueueSize": 4194304
  },
  "NodeInfoPrivacy": false,
  "NodeInfo": {
        "name": "xxx"

    }
}
```

**Comment by neilalexander** [comment]
Just as an FYI, you will need to generate new keys now, as you have posted your private keys here.
