### ISSUE TITLE
Android Yggdrasil native lib crashes after Yggdrasil().stop() method call

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-go#714]
The issue reproduces permanently for v 0.3.14 Android build:

Build log:
```
go get -u github.com/yggdrasil-network/yggdrasil-go;
package github.com/yggdrasil-network/yggdrasil-go: no Go files in /home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go
make: [Makefile:4: all] Error 1 (ignored)
cd /home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go; \
	go get -v -d ./...; \
	go get -u github.com/yggdrasil-network/yggdrasil-extras; \
	ANDROID=true ./build;
Building aar for Android
mv /home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go/yggdrasil.aar yggdrasil.aar;
mv /home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go/yggdrasil-sources.jar yggdrasil-sources.jar;
```

Crash log:
```
I/GoLog: Stopping...
I/GoLog: Failed to accept connection: accept tcp [fe80::15:b2ff:fe00:0%wlan0]:37917: use of closed network connection
I/GoLog: Stopping TCP listener on: [fe80::15:b2ff:fe00:0%wlan0]:37917
    Disconnected TCP: 201:b614:c68e:b27f:dc0e:e8ec:15d0:2eb0@88.201.129.205, source 10.0.2.16; error: message error: read tcp 10.0.2.16:41168->88.201.129.205:8777: use of closed network connection
I/GoLog: Disconnected TCP: 200:e6bd:2cff:628e:bfb8:a636:d600:306b@194.177.21.156, source 10.0.2.16; error: message error: read tcp 10.0.2.16:38132->194.177.21.156:5066: use of closed network connection
I/GoLog: Disconnected TCP: 201:e64d:1a9:d2b0:9c74:f285:ea73:5e05@188.226.125.64, source 10.0.2.16; error: message error: read tcp 10.0.2.16:46268->188.226.125.64:54321: use of closed network connection
I/GoLog: DEBUG: stopped handler for tcp://188.226.125.64:54321 message error: read tcp 10.0.2.16:46268->188.226.125.64:54321: use of closed network connection
I/GoLog: DEBUG: stopped handler for tcp://88.201.129.205:8777 message error: read tcp 10.0.2.16:41168->88.201.129.205:8777: use of closed network connection
I/GoLog: DEBUG: stopped handler for tcp://194.177.21.156:5066 message error: read tcp 10.0.2.16:38132->194.177.21.156:5066: use of closed network connection
    Stopped
I/GoLog: Stopping...
E/Go: panic: close of closed channel
    goroutine 1841 [running]:
    github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*link).stop(...)
    	/home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/link.go:146
    github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil.(*Core)._stop(0x8fcca700)
    	/home/vadym/go/src/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil/core.go:200 +0xba
    github.com/Arceliar/phony.Block.func1()
    	/tmp/gomobile-work-168739983/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:89 +0x24
    github.com/Arceliar/phony.(*Inbox).run(0x8fcca700)
    	/tmp/gomobile-work-168739983/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:104 +0xaf
    created by github.com/Arceliar/phony.(*Inbox).restart
    	/tmp/gomobile-work-168739983/pkg/mod/github.com/!arceliar/phony@v0.0.0-20191006174943-d0c68492aca0/actor.go:130 +0x39
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9836 (osx88.yggdrasil), pid 9776 (osx88.yggdrasil)
```

Duplicated in:
https://github.com/yggdrasil-network/yggdrasil-extras/issues/7

**Comment by Arceliar** [comment]
It looks like `yggdrasil.Core.Stop()` is being called twice. The first time it runs (between `Stopping...` and `Stopped`), shutdown appears to work normally. The second time crashes, because some channels have already been closed to signal that things should stop. We could add some sort of protection to prevent `Stop()` from being run a second time, but that makes incorrect use harder to diagnose (so the most I would consider is having it panic, but with a more useful help message than this).

Since this doesn't happen on other platforms, my guess is that the problem is in either `yggdrasil-extras` or the Android code (wherever `Stop()` is getting called a second time).

**Comment by vikulin** [comment]
Hi @Arceliar . I reviewed the code from https://github.com/yggdrasil-network/yggdrasil-extras/ project and found the issue:

https://github.com/yggdrasil-network/yggdrasil-extras/blob/master/src/mobile/mobile.go#L115

there is Stop() which invoked second time. I tried to fix it and left only the line and it worked:

```
// Stop the mobile Yggdrasil instance
func (m *Yggdrasil) Stop() {
	//m.admin.Stop()
	//m.core.Stop()
	m.Stop()
}
```

But still I'm seeing an issue when I start Yggdrasil second time. There is no traffic. Could you please confirm that Stop() function closes all resources correctly including admin module: I found that function doesn't:

https://github.com/yggdrasil-network/yggdrasil-go/blob/78b5f88e4bb734d0dd6a138ff08d34ca39dcaea3/src/yggdrasil/core.go#L195

```
// Stop shuts down the Yggdrasil node.
func (c *Core) Stop() {
	phony.Block(c, c._stop)
}

// This function is unsafe and should only be ran by the core actor.
func (c *Core) _stop() {
	c.log.Infoln("Stopping...")
	if c.addPeerTimer != nil {
		c.addPeerTimer.Stop()
	}
	c.link.stop()
	for _, peer := range c.GetPeers() {
		c.DisconnectPeer(peer.Port)
	}
	c.log.Infoln("Stopped")
}
```

**Comment by vikulin** [comment]
@neilalexander , @Arceliar after so many attempts (I'm totally nuwbie in Go and even don't know the syntax) I have fixed the issue. Please review my changes:

https://github.com/yggdrasil-network/yggdrasil-extras/pull/8/files

**Comment by vikulin** [comment]
Relates to #720
