### ISSUE TITLE
[future branch] app crashes with error "panic: runtime error: slice bounds out of range [32:30]"

### ISSUE THREAD

**Issue by vikulin** [yggdrasil-network/yggdrasil-go#787]
```
vadym@ubuntu:~/Downloads$ sudo ./yggdrasil -useconf < ./yggdrasil.conf
[sudo] password for vadym: 
2021/06/06 02:42:14 Build name: yggdrasil-future
2021/06/06 02:42:14 Build version: 0.3.16-97-ge7da3d7
2021/06/06 02:42:14 Starting up...
2021/06/06 02:42:14 Startup complete
2021/06/06 02:42:14 Listening for TCP on: 127.0.0.1:4040
2021/06/06 02:42:14 Starting multicast module
2021/06/06 02:42:14 TCP admin socket listening on 127.0.0.1:9001
2021/06/06 02:42:14 Listening for TCP on: [fe80::5207:4518:4378:7f1%ens33]:34691
2021/06/06 02:42:14 Interface name: tun0
2021/06/06 02:42:14 Interface IPv6: 202:d7cd:bd04:6bbc:acc6:b002:da12:86c7/7
2021/06/06 02:42:14 Interface MTU: 53049
2021/06/06 02:42:14 Your public key is 2506485f72886a6729ffa4bdaf270a8801b283d30aed4ea1f14518e5e8f7e9f6
2021/06/06 02:42:14 Your IPv6 address is 202:d7cd:bd04:6bbc:acc6:b002:da12:86c7
2021/06/06 02:42:14 Your IPv6 subnet is 302:d7cd:bd04:6bbc::/64
panic: runtime error: slice bounds out of range [32:30]

goroutine 23 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/multicast.(*Multicast).listen(0xc000098060)
	/home/vadym/yggdrasil-go-parent/yggdrasil-go/src/multicast/multicast.go:353 +0x8a5
created by github.com/yggdrasil-network/yggdrasil-go/src/multicast.(*Multicast)._start
	/home/vadym/yggdrasil-go-parent/yggdrasil-go/src/multicast/multicast.go:101 +0x2e6
```

**Comment by vikulin** [comment]
Probably fixed in https://github.com/yggdrasil-network/yggdrasil-go/pull/781

**Comment by vikulin** [comment]
Fixed.
