### ISSUE TITLE
Yggdrasil in LXC

### ISSUE THREAD

**Issue by fingolfin0** [yggdrasil-network/yggdrasil-go#838]
Hello. I tried to install yggdrasil in LXC container, but got an error:
```
2021/09/14 17:45:02 Build name: yggdrasil
2021/09/14 17:45:02 Build version: 0.4.0
2021/09/14 17:45:02 Starting up...
2021/09/14 17:45:02 Startup complete
2021/09/14 17:45:02 Starting multicast module
panic: CreateTUN("\x00") failed; /dev/net/tun does not exist

goroutine 27 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc0000a2000, 0xc00012a780, 0x4, 0xc0001282a0, 0x28, 0xcf39, 0x28, 0x0)
        /home/circleci/project/src/tuntap/tun_linux.go:19 +0x31c
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0xc0000a2000, 0x0, 0x0)
        /home/circleci/project/src/tuntap/tun.go:136 +0x335
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        /home/circleci/project/src/tuntap/tun.go:108 +0x33
github.com/Arceliar/phony.Block.func1()
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:80 +0x2f
github.com/Arceliar/phony.(*Inbox).run(0xc0000a2048)
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:89 +0x3d
created by github.com/Arceliar/phony.(*Inbox).restart
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:121 +0x3f
```
My host's OS is manjaro, and container's OS is debian bullseye. I tried to fix this via [this answer](https://stackoverflow.com/questions/23706652/tap-tun-adapter-in-lxc-container) from stackoverflow, and got another error:
```
2021/09/14 17:50:33 Build name: yggdrasil
2021/09/14 17:50:33 Build version: 0.4.0
2021/09/14 17:50:33 Starting up...
2021/09/14 17:50:33 Startup complete
2021/09/14 17:50:33 Starting multicast module
panic: operation not permitted

goroutine 50 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc000142150, 0xc000134060, 0x4, 0xc000284060, 0x28, 0xcf39, 0x28, 0x0)
        /home/circleci/project/src/tuntap/tun_linux.go:19 +0x31c
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start(0xc000142150, 0x0, 0x0)
        /home/circleci/project/src/tuntap/tun.go:136 +0x335
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start.func1()
        /home/circleci/project/src/tuntap/tun.go:108 +0x33
github.com/Arceliar/phony.Block.func1()
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:80 +0x2f
github.com/Arceliar/phony.(*Inbox).run(0xc000142198)
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:89 +0x3d
created by github.com/Arceliar/phony.(*Inbox).restart
        /go/pkg/mod/github.com/!arceliar/phony@v0.0.0-20210209235338-dde1a8dca979/actor.go:121 +0x3f
```
Please let us know if this error can be solved only by configuring LXC, or is it a bug in yggdrasil? If I can help you, I am ready to test various configurations in containers.

**Comment by neilalexander** [comment]
This is not an Yggdrasil bug, but rather that LXC is not exposing your kernel’s `tun` module inside the containers.

You can try something like: https://www.cloudhosting.lv/eng/faq/How-to-enable-tun-tap-inside-LXC
