### ISSUE TITLE
crash when accessing some addresses

### ISSUE THREAD

**Issue by collabviem1** [yggdrasil-network/yggdrasil-go#860]
If you try to ping some very high address like `2ff::` yggdrasil crashes. I can't provide much more info, you can try for yourself, it is very easy to reproduce the bug.

**Comment by neilalexander** [comment]
Can you at the very least provide the panic log output and an address that you tried pinging?

**Comment by neilalexander** [comment]
Appears to be this:
```
panic: runtime error: index out of range [32] with length 32

goroutine 9 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/address.(*Address).GetKey(0xc000280610)
        /Volumes/Workspace/yggdrasil-go/src/address/address.go:132 +0x185
github.com/yggdrasil-network/yggdrasil-go/src/ipv6rwc.(*keyStore).sendToAddress(0xc00005c0c0, {0x2, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Volumes/Workspace/yggdrasil-go/src/ipv6rwc/ipv6rwc.go:97 +0x358
github.com/yggdrasil-network/yggdrasil-go/src/ipv6rwc.(*keyStore).writePC(0xc00005c0c0, {0xc000294004, 0x38, 0x10003})
        /Volumes/Workspace/yggdrasil-go/src/ipv6rwc/ipv6rwc.go:290 +0x385
github.com/yggdrasil-network/yggdrasil-go/src/ipv6rwc.(*ReadWriteCloser).Write(...)
        /Volumes/Workspace/yggdrasil-go/src/ipv6rwc/ipv6rwc.go:347
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).read(0xc00013a150)
        /Volumes/Workspace/yggdrasil-go/src/tuntap/iface.go:20 +0xba
created by github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter)._start
        /Volumes/Workspace/yggdrasil-go/src/tuntap/tun.go:144 +0x513
exit status 2
```
